# Generated by Django 3.1.4 on 2020-12-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalPortfolio', '0003_auto_20201223_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
