# Generated by Django 3.1.4 on 2020-12-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalPortfolio', '0004_auto_20201223_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200),
        ),
    ]
